FROM racket/racket:7.9-cs-full AS build

WORKDIR /opt/shorty
COPY .git /opt/shorty/.git
COPY ci /opt/shorty/ci
COPY shorty /opt/shorty/shorty
COPY migrations /opt/shorty/migrations
COPY resources /opt/shorty/resources
COPY static /opt/shorty/static

RUN ci/setup-catalogs.sh
RUN raco pkg install -D --auto --batch \
  shorty/ \
  shorty-tests/
CMD ["raco", "test", "/opt/shorty/shorty-tests"]
